name: Sync any source updates
on:
  workflow_dispatch:
  schedule:
  - cron:  '0 2 * * *'

permissions:
  contents: write

jobs:
  update:
    uses: OpenVoxProject/shared-actions/.github/workflows/sync.yml@main
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.OPENVOXBOT_COMMIT_AND_PRS }}
